import { Activity, AppWindow, BookOpenText, Bot, BrainCircuit, Camera, Database, FileSearch, Headphones, Home, Languages, MessageSquareText, Music2, Search, ShieldCheck, TerminalSquare, Wrench } from "lucide-react";
import { toast } from "sonner";

type CapabilityRoom = { name: string; function: string; providers: string; status: "add api" | "desktop adapter" | "local package" | "optional"; owner: "Developer" | "User account" | "Local desktop"; credential: "Not connected" | "No cloud credential" | "Internal service" | "User authorisation"; icon: typeof Bot };

const rooms: CapabilityRoom[] = [
  { name: "Reasoning & conversation", function: "Natural-language discussion, planning, and tool selection", providers: "OpenAI · Anthropic · compatible LLM", status: "add api", owner: "Developer", credential: "Not connected", icon: BrainCircuit },
  { name: "Speech & language", function: "Speech-to-text, spoken response, translation, language switching", providers: "OpenAI Audio · Azure Speech · ElevenLabs", status: "add api", owner: "Developer", credential: "Not connected", icon: Languages },
  { name: "Wake word", function: "Private local ‘Arthur’ trigger", providers: "openWakeWord", status: "local package", owner: "Local desktop", credential: "No cloud credential", icon: Headphones },
  { name: "Web research", function: "Approved sources, search retrieval, spoken summaries", providers: "SerpAPI · Brave Search · Tavily", status: "add api", owner: "Developer", credential: "Not connected", icon: Search },
  { name: "Files & documents", function: "Selected-file analysis, OCR, and constrained extraction", providers: "Vision/OCR provider · local parser", status: "optional", owner: "Local desktop", credential: "No cloud credential", icon: FileSearch },
  { name: "Vision & camera", function: "Optional image context and identity verification", providers: "Luxand · vision model", status: "add api", owner: "Developer", credential: "Not connected", icon: Camera },
  { name: "Profiles & notes", function: "Account identity, private notes, user-controlled memory", providers: "Arthur private database · Supabase optional", status: "optional", owner: "User account", credential: "Internal service", icon: Database },
  { name: "Music", function: "Original-song generation or authorised playback routing", providers: "Music model · Piped-compatible · BhariyaMusic", status: "add api", owner: "Developer", credential: "Not connected", icon: Music2 },
  { name: "Smart home", function: "Consent-first devices, lighting, climate, and routines", providers: "Home Assistant", status: "add api", owner: "User account", credential: "User authorisation", icon: Home },
  { name: "Calendar & productivity", function: "Authorised schedules, briefs, and reminders", providers: "Google Workspace · Microsoft Graph · custom API", status: "add api", owner: "User account", credential: "User authorisation", icon: BookOpenText },
  { name: "Messages", function: "Draft and send only after explicit approval", providers: "Email · Slack · Discord · custom API", status: "add api", owner: "User account", credential: "User authorisation", icon: MessageSquareText },
  { name: "Local Windows control", function: "Reviewed apps, files, settings, and diagnostics", providers: "Arthur Windows adapter", status: "desktop adapter", owner: "Local desktop", credential: "No cloud credential", icon: AppWindow },
  { name: "Developer extensions", function: "Declared plugins and safe custom HTTPS tools", providers: "Plugin contract · Custom API room", status: "optional", owner: "Developer", credential: "Not connected", icon: Wrench },
];

export default function CapabilityRegistry({ openIntegration }: { openIntegration: () => void }) {
  return <section className="capability-registry"><header className="capability-heading"><div><span className="eyebrow">API capability rooms / function classified</span><h2>Arthur routes work only to an approved room.</h2><p>This is an extensible capability catalogue, not a claim that every internet API is already connected. A room stays unavailable until its developer-approved provider or local adapter is ready.</p></div><div className="capability-seal"><ShieldCheck size={22} /><span>CHECK<br />RESOURCE</span></div></header><div className="capability-grid">{rooms.map((room) => { const Icon = room.icon; return <article className={`capability-room ${room.status.replace(" ", "-")}`} key={room.name}><span className="capability-icon"><Icon size={18} /></span><div><span className="eyebrow">{room.status}</span><h3>{room.name}</h3><p>{room.function}</p><small>{room.providers}</small><div className="capability-meta"><span>Owner <b>{room.owner}</b></span><span>Credential <b>{room.credential}</b></span></div></div><button className="text-button" onClick={() => room.status === "add api" ? openIntegration() : toast(`${room.name} is ${room.status}.`, { description: `${room.owner} owns this room. Credential state: ${room.credential}.` })}>{room.status === "add api" ? "Add API" : "Inspect"}</button></article>;})}</div><section className="provider-watch"><span className="provider-watch-icon"><Activity size={18} /></span><div><span className="eyebrow">Provider update watch</span><h3>Not scheduled: no connected provider may be checked yet.</h3><p>When the developer connects a provider, Arthur can use a server-side scheduled health/version check with rate limits, credential-safe requests, and an audit record. The browser preview never polls third-party APIs.</p></div><button className="outline-button" onClick={() => toast("Scheduled provider checks require a configured server job and a connected provider.", { description: "See PROVIDER_UPDATE_CHECKS.md in the project for the required safeguards." })}>Review policy</button></section><footer className="capability-footer"><TerminalSquare size={18} /><p><b>Command boundary:</b> reviewed Windows commands use a local desktop adapter, not an internet API. If a requested provider room is unavailable, Arthur stops and explains the missing resource—it never invents a connection or runs raw shell text.</p></footer></section>;
}
